version: "3.9"
services:
  mongo:
    image: mongo:5.0.10
    # Provide mongo config
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    # Set health checks to wait until mongo has started
    #volumes:
    # -  ./data-vol:/data/db 
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5
    # Maps tcp port to host
    #ports:
    #  - 27017:27017
    
  mqtt:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1884:1884
    volumes:
      - ./mosquitto:/mosquitto/config
    healthcheck:
      test: ["CMD-SHELL", mosquitto_sub -p 1884 -t 'topic' -C 1 -E -i probe -W 3]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s   
      
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT-TT
    container_name: aas-env
    volumes:
      - ./aas-env.properties:/application/application.properties
      - ./aas:/application/aas
    ports:
        - 8081:8081
    depends_on:
        mongo:
            condition: service_healthy
        mqtt:
            condition: service_healthy
        aas-registry:
            condition: service_healthy
        sm-registry:
            condition: service_healthy
            
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - 8082:8080
    volumes:
      - ./aas-registry.yml:/workspace/config/application.yml
    depends_on:
      mongo:
        condition: service_healthy
    
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: submodel_registry
    ports:
      - 8083:8080
    volumes:
      - ./sm-registry.yml:/workspace/config/application.yml
    depends_on:
      mongo:
        condition: service_healthy

  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    ports:
      - 8084:8081
    volumes:
      - ./aas-discovery.properties:/application/application.properties
    depends_on:
      mongo:
        condition: service_healthy
      
#  aas-web-ui_v2:
#    image: eclipsebasyx/aas-gui:v2-231107
#    container_name: aas-ui
#    ports:
#      - "3000:3000"
#    environment:
#      VITE_REGISTRY_PATH: "http://192.168.178.42/registry"
#      VITE_AAS_REPO_PATH: "http://192.168.178.42/aas-repo/shells"
#      VITE_SUBMODEL_REPO_PATH: "http://192.168.178.42/submodel-repo/submodels"
#      VITE_CD_REPO_PATH: "http://192.168.178.42/concept-descriptions"
#    restart: always


  # AAS Web UI
  aas-ui:
    image: eclipsebasyx/aas-gui:v2-240125
    container_name: aas-ui
#    ports:
#      - "3000:3000"
    environment:
      VITE_AAS_REGISTRY_PATH: "/registry"
      VITE_SUBMODEL_REGISTRY_PATH: "/subregistry"
      VITE_AAS_REPO_PATH: "/aas-repo/shells"
      VITE_SUBMODEL_REPO_PATH: "/submodel-repo/submodels"
      VITE_CD_REPO_PATH: "/cd-repo/concept-descriptions"
      VITE_PRIMARY_COLOR: "#76b900"
    volumes:
      - ./logo:/app/src/assets/Logo
    restart: always

  databridge:
    image: eclipsebasyx/databridge:1.0.0-SNAPSHOT
    container_name: databridge-device-integration
    volumes:
      - ./databridge:/usr/share/config
    depends_on:
        mongo:
            condition: service_healthy
        mqtt:
            condition: service_healthy

  ipaemulator:
    container_name: ipaemulator
    image: ipafab/prodatexemulator:1.0
    ports:
      - 5050-5055:5050-5055

  prodatexui:
    container_name: prodatexui
    image: ipafab/prodatexuiserver:latest
    ports:
      - 81:8080

  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    restart: always
